// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: protodecode/protodemo/demo.proto

package protodemo

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecodeDemo contains many types to test decoding.
// See: https://developers.google.com/protocol-buffers/docs/proto3#scalar
type DecodeDemo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int64Value    int64                  `protobuf:"varint,1,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	StringValue   string                 `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue    []byte                 `protobuf:"bytes,3,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Any           *anypb.Any             `protobuf:"bytes,5,opt,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeDemo) Reset() {
	*x = DecodeDemo{}
	mi := &file_protodecode_protodemo_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeDemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeDemo) ProtoMessage() {}

func (x *DecodeDemo) ProtoReflect() protoreflect.Message {
	mi := &file_protodecode_protodemo_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeDemo.ProtoReflect.Descriptor instead.
func (*DecodeDemo) Descriptor() ([]byte, []int) {
	return file_protodecode_protodemo_demo_proto_rawDescGZIP(), []int{0}
}

func (x *DecodeDemo) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *DecodeDemo) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *DecodeDemo) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *DecodeDemo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DecodeDemo) GetAny() *anypb.Any {
	if x != nil {
		return x.Any
	}
	return nil
}

var File_protodecode_protodemo_demo_proto protoreflect.FileDescriptor

const file_protodecode_protodemo_demo_proto_rawDesc = "" +
	"\n" +
	" protodecode/protodemo/demo.proto\x12\tprotodemo\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xd3\x01\n" +
	"\n" +
	"DecodeDemo\x12\x1f\n" +
	"\vint64_value\x18\x01 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fstring_value\x18\x02 \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x03 \x01(\fR\n" +
	"bytesValue\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x03any\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x03anyB.Z,github.com/evanj/hacks/protodecode/protodemob\x06proto3"

var (
	file_protodecode_protodemo_demo_proto_rawDescOnce sync.Once
	file_protodecode_protodemo_demo_proto_rawDescData []byte
)

func file_protodecode_protodemo_demo_proto_rawDescGZIP() []byte {
	file_protodecode_protodemo_demo_proto_rawDescOnce.Do(func() {
		file_protodecode_protodemo_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protodecode_protodemo_demo_proto_rawDesc), len(file_protodecode_protodemo_demo_proto_rawDesc)))
	})
	return file_protodecode_protodemo_demo_proto_rawDescData
}

var file_protodecode_protodemo_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protodecode_protodemo_demo_proto_goTypes = []any{
	(*DecodeDemo)(nil),            // 0: protodemo.DecodeDemo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 2: google.protobuf.Any
}
var file_protodecode_protodemo_demo_proto_depIdxs = []int32{
	1, // 0: protodemo.DecodeDemo.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: protodemo.DecodeDemo.any:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protodecode_protodemo_demo_proto_init() }
func file_protodecode_protodemo_demo_proto_init() {
	if File_protodecode_protodemo_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protodecode_protodemo_demo_proto_rawDesc), len(file_protodecode_protodemo_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protodecode_protodemo_demo_proto_goTypes,
		DependencyIndexes: file_protodecode_protodemo_demo_proto_depIdxs,
		MessageInfos:      file_protodecode_protodemo_demo_proto_msgTypes,
	}.Build()
	File_protodecode_protodemo_demo_proto = out.File
	file_protodecode_protodemo_demo_proto_goTypes = nil
	file_protodecode_protodemo_demo_proto_depIdxs = nil
}
